
logging:
  level:
    root: info
  file:
#    name: my-spring-boot.log
    path: D:/temp

pay:
  merchantIds:
    - 102380
    - 234809
    - 238400

  orderIds: or1304,or12309,or2301
  app-key: ha238a8230uhasf

order:
  base-url: http://localhost/order
  app-key: aj282hfa0023r0
  extra:
    parentKey:
      key1: value1
      key2: value2
  expire-time: 180d

spring:
  task:
    execution:
      pool:
        max-size: 10
        queue-capacity: 10
  data:
    redis:
#      database:
#      host:
#      port:
#      password:
#      ssl:
#      timeout: 3s
#      connectTimeout: 3s
#      clientName:
#      cluster:
#        nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
#        max-redirects: 3

#      sentinel:
#        master:
#        nodes:
  redis:
    redisson:
      file: classpath:redisson.yaml

base64:
  decryption:
    enable: true

server:
  port: 18080
