logging:
  level:
    root: info
  file:
#    name: my-spring-boot.log
    path: D:/temp

pay:
  merchantIds:
    - 102380
    - 234809
    - 238400

  orderIds: or1304,or12309,or2301
  app-key: ha238a8230uhasf

order:
  base-url: http://localhost/order
  app-key: aj282hfa0023r0
  extra:
    parentKey:
      key1: value1
      key2: value2
  expire-time: 180d

spring:
  task:
    execution:
      pool:
        max-size: 10
        queue-capacity: 10

base64:
  decryption:
    enable: true



